"""Public, backend-independent MemLint foundation API."""

from memlint.checkers import (
    CHECKER_RESULT_SCHEMA_VERSION,
    SCOPE_POLICY_SCHEMA_VERSION,
    Checker,
    CheckerCost,
    CheckerError,
    CheckerInputError,
    CheckerResult,
    CheckerStats,
    EvidenceItem,
    Finding,
    OrphanedProvenanceChecker,
    PrincipalBoundaryRule,
    PrivacyScopeViolationChecker,
    RedundancyBloatChecker,
    ScopeDimension,
    ScopeIsolationPolicy,
    StaleActiveChecker,
    load_scope_policy,
)
from memlint.models import (
    MemoryScope,
    NormalizedMemory,
    NormalizedStore,
    ProvenanceStatus,
    SourceRef,
    Transcript,
    TranscriptSet,
    TranscriptTurn,
)
from memlint.mutations import (
    BaseStoreStatus,
    ConflictRelation,
    DistractorFamily,
    GoldLabel,
    GoldLabelUnit,
    MutationError,
    MutationManifest,
    MutationPreconditionError,
    MutationRequest,
    MutationResult,
    RetrievalProbe,
    mutate,
)
from memlint.taxonomy import TAXONOMY_VERSION, DefectClass

__all__ = [
    "CHECKER_RESULT_SCHEMA_VERSION",
    "Checker",
    "CheckerCost",
    "CheckerError",
    "CheckerInputError",
    "CheckerResult",
    "CheckerStats",
    "EvidenceItem",
    "Finding",
    "MemoryScope",
    "BaseStoreStatus",
    "ConflictRelation",
    "DefectClass",
    "DistractorFamily",
    "GoldLabel",
    "GoldLabelUnit",
    "MutationError",
    "MutationManifest",
    "MutationPreconditionError",
    "MutationRequest",
    "MutationResult",
    "NormalizedMemory",
    "NormalizedStore",
    "OrphanedProvenanceChecker",
    "PrincipalBoundaryRule",
    "PrivacyScopeViolationChecker",
    "RedundancyBloatChecker",
    "SCOPE_POLICY_SCHEMA_VERSION",
    "ScopeDimension",
    "ScopeIsolationPolicy",
    "StaleActiveChecker",
    "ProvenanceStatus",
    "SourceRef",
    "Transcript",
    "TranscriptSet",
    "TranscriptTurn",
    "RetrievalProbe",
    "TAXONOMY_VERSION",
    "load_scope_policy",
    "mutate",
]

__version__ = "0.1.0"
